# Generated by Django 2.1.8 on 2019-04-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailvideos', '0010_video_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='file_hash',
            field=models.CharField(blank=True, editable=False, max_length=40),
        ),
    ]
